/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.trabajofinal.ui;
import java.util.ArrayList;
import com.mycompany.trabajofinal.controladores.CargoControlador;
import com.mycompany.trabajofinal.controladores.DocenteControlador;
import com.mycompany.trabajofinal.objetos.Cargo;
import com.mycompany.trabajofinal.objetos.Persona;
import com.mycompany.trabajofinal.objetos.Docente;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;



/**
 *
 * @author maximiliano
 */
public class ABMDocente extends javax.swing.JInternalFrame {

        DocenteControlador docenteControlador;
        ArrayList<Docente> docentes;
        ArrayList<Persona> personas;
        ArrayList<Cargo> cargos;
        
    public ABMDocente() throws SQLException, ClassNotFoundException {
        initComponents();
        docenteControlador = new DocenteControlador();
        docentes = new ArrayList<Docente>();
        personas = new ArrayList<Persona>();
        cargos = new ArrayList<Cargo>();
        docenteControlador.llenarTablaDocente(tabla);
        personas = docenteControlador.llenarComboPersona();
        for (int i = 0; i < personas.size(); i++) {
            cbPersonas.addItem(personas.get(i).getNombre()+" -- "+personas.get(i).getApellido()+" -- "+personas.get(i).getDocumento());
            }
        
        cargos = docenteControlador.llenarComboCargo();
        for (int i = 0; i < cargos.size(); i++) {
            cbCargos.addItem(cargos.get(i).getCodigo()+" -- "+cargos.get(i).getDescripcion());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLegajo = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        cbPersonas = new javax.swing.JComboBox<>();
        cbCargos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setResizable(true);
        setTitle("Turnos");
        setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel1.setText("DOCENTES");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel2.setText("Legajo:");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel3.setText("Persona:");

        txtLegajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLegajoKeyTyped(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificar.setText("Modificar");

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla);

        cbPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una persona..." }));

        cbCargos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un cargo..." }));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel4.setText("Cargo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(btnAgregar))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(btnEliminar)
                                        .addGap(40, 40, 40)
                                        .addComponent(btnModificar)
                                        .addGap(130, 130, 130)
                                        .addComponent(btnSalir))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtLegajo, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                            .addComponent(jLabel1)
                                            .addComponent(cbPersonas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbCargos, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar)
                    .addComponent(btnSalir))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Docente docente = new Docente();
        Persona persona = new Persona();
        Cargo cargo = new Cargo();
        
        int legajo = (Integer.parseInt(txtLegajo.getText()));
        
        Integer idPersona = personas.get(cbPersonas.getSelectedIndex()-1).getId_persona();
        String nombre = personas.get(cbPersonas.getSelectedIndex()-1).getNombre();
        String apellido = personas.get(cbPersonas.getSelectedIndex()-1).getApellido();
        int documento = personas.get(cbPersonas.getSelectedIndex()-1).getDocumento();
        Date fecha = personas.get(cbPersonas.getSelectedIndex()-1).getFecha_nacimiento();
        String sexo = personas.get(cbPersonas.getSelectedIndex()-1).getSexo();
        
        Integer idCargo = cargos.get(cbCargos.getSelectedIndex()-1).getId_cargo();
        int codigo = cargos.get(cbCargos.getSelectedIndex()-1).getCodigo();
        String descripcion = cargos.get(cbCargos.getSelectedIndex()-1).getDescripcion();
        
        persona.setId_persona(idPersona);
        persona.setNombre(nombre);
        persona.setApellido(apellido);
        persona.setDocumento(documento);
        persona.setFecha_nacimiento(fecha);
        persona.setSexo(sexo);
        
        cargo.setId_cargo(idCargo);
        cargo.setCodigo(codigo);
        cargo.setDescripcion(descripcion);
        
        docente.setLegajo(legajo);
        docente.setPersona(persona);
        docente.setCargo(cargo);
        docenteControlador.insertarDocente(docente, persona, cargo, tabla);
//        if (descripcion.length() < 3)
//            JOptionPane.showMessageDialog(this, "Debe ingresar más de 3 caracteres");
//        else if (codigo == 0 )
//            JOptionPane.showMessageDialog(this, "Debe ingresar un número que no sea 0");
//        else
//            
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Docente docente = new Docente();
        int row = tabla.getSelectedRow();
        String id = tabla.getValueAt(row, 0).toString();
        docente.setId_docente(Integer.parseInt(id));
        
        docenteControlador.eliminarDocente(docente, tabla);
        
        limpiarCampos();
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtLegajoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLegajoKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car)){
            JOptionPane.showMessageDialog(this, "Este campo no acepta Letras");
            evt.consume();
        }
    }//GEN-LAST:event_txtLegajoKeyTyped
    public void limpiarCampos(){
        txtLegajo.setText("");
        
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCargos;
    private javax.swing.JComboBox<String> cbPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtLegajo;
    // End of variables declaration//GEN-END:variables
}
